// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: deps.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Dependency struct {
	Organization         *string  `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
	Module               *string  `protobuf:"bytes,2,opt,name=module" json:"module,omitempty"`
	VersionConstraint    *string  `protobuf:"bytes,3,opt,name=versionConstraint" json:"versionConstraint,omitempty"`
	Scopes               []string `protobuf:"bytes,4,rep,name=scopes" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a878629c37a3cae, []int{0}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetOrganization() string {
	if m != nil && m.Organization != nil {
		return *m.Organization
	}
	return ""
}

func (m *Dependency) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func (m *Dependency) GetVersionConstraint() string {
	if m != nil && m.VersionConstraint != nil {
		return *m.VersionConstraint
	}
	return ""
}

func (m *Dependency) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type DependencyManagementFile struct {
	Language             *string       `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	System               *string       `protobuf:"bytes,2,opt,name=system" json:"system,omitempty"`
	Organization         *string       `protobuf:"bytes,5,opt,name=organization" json:"organization,omitempty"`
	Module               *string       `protobuf:"bytes,6,opt,name=module" json:"module,omitempty"`
	Version              *string       `protobuf:"bytes,7,opt,name=version" json:"version,omitempty"`
	Dependencies         []*Dependency `protobuf:"bytes,8,rep,name=dependencies" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DependencyManagementFile) Reset()         { *m = DependencyManagementFile{} }
func (m *DependencyManagementFile) String() string { return proto.CompactTextString(m) }
func (*DependencyManagementFile) ProtoMessage()    {}
func (*DependencyManagementFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a878629c37a3cae, []int{1}
}
func (m *DependencyManagementFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyManagementFile.Unmarshal(m, b)
}
func (m *DependencyManagementFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyManagementFile.Marshal(b, m, deterministic)
}
func (m *DependencyManagementFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyManagementFile.Merge(m, src)
}
func (m *DependencyManagementFile) XXX_Size() int {
	return xxx_messageInfo_DependencyManagementFile.Size(m)
}
func (m *DependencyManagementFile) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyManagementFile.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyManagementFile proto.InternalMessageInfo

func (m *DependencyManagementFile) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *DependencyManagementFile) GetSystem() string {
	if m != nil && m.System != nil {
		return *m.System
	}
	return ""
}

func (m *DependencyManagementFile) GetOrganization() string {
	if m != nil && m.Organization != nil {
		return *m.Organization
	}
	return ""
}

func (m *DependencyManagementFile) GetModule() string {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return ""
}

func (m *DependencyManagementFile) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *DependencyManagementFile) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*Dependency)(nil), "cloud.deps.dependency_extractor.api.Dependency")
	proto.RegisterType((*DependencyManagementFile)(nil), "cloud.deps.dependency_extractor.api.DependencyManagementFile")
}

func init() { proto.RegisterFile("deps.proto", fileDescriptor_8a878629c37a3cae) }

var fileDescriptor_8a878629c37a3cae = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4a, 0xf4, 0x40,
	0x10, 0xc4, 0xc9, 0x97, 0x6f, 0xff, 0xd8, 0xee, 0xc5, 0x39, 0xc8, 0xe0, 0x29, 0xc4, 0xcb, 0x1e,
	0x24, 0x82, 0x8f, 0xa0, 0xe2, 0xcd, 0xcb, 0x7a, 0xf3, 0x22, 0x4d, 0xa6, 0x09, 0x03, 0x49, 0xf7,
	0x30, 0x33, 0x11, 0xd7, 0x87, 0xf0, 0x7d, 0xbd, 0xc9, 0xce, 0x66, 0xb3, 0x84, 0x05, 0xf1, 0xf8,
	0xeb, 0x6a, 0x8a, 0xaa, 0x02, 0x30, 0xe4, 0x42, 0xe5, 0xbc, 0x44, 0x51, 0xd7, 0x75, 0x2b, 0xbd,
	0xa9, 0xd2, 0xc5, 0x90, 0x23, 0x36, 0xc4, 0xf5, 0xf6, 0x8d, 0x3e, 0xa2, 0xc7, 0x3a, 0x8a, 0xaf,
	0xd0, 0xd9, 0xf2, 0x2b, 0x03, 0x78, 0x1c, 0x45, 0x55, 0xc2, 0x4a, 0x7c, 0x83, 0x6c, 0x3f, 0x31,
	0x5a, 0x61, 0x9d, 0x15, 0xd9, 0xfa, 0x6c, 0x33, 0xb9, 0xa9, 0x4b, 0x98, 0x77, 0x62, 0xfa, 0x96,
	0xf4, 0xbf, 0xa4, 0x0e, 0xa4, 0x6e, 0xe0, 0xe2, 0x9d, 0x7c, 0xb0, 0xc2, 0x0f, 0xc2, 0x21, 0x7a,
	0xb4, 0x1c, 0x75, 0x9e, 0x5e, 0x4e, 0x85, 0x9d, 0x4b, 0xa8, 0xc5, 0x51, 0xd0, 0xff, 0x8b, 0x7c,
	0xe7, 0xb2, 0xa7, 0xf2, 0x3b, 0x03, 0x7d, 0x0c, 0xf4, 0x8c, 0x8c, 0x0d, 0x75, 0xc4, 0xf1, 0xc9,
	0xb6, 0xa4, 0xae, 0x60, 0xd9, 0x22, 0x37, 0x3d, 0x36, 0x34, 0x44, 0x1b, 0x39, 0x19, 0x6e, 0x43,
	0xa4, 0xee, 0x10, 0x6b, 0x4f, 0x27, 0x95, 0x66, 0xbf, 0x56, 0x9a, 0x4f, 0x2a, 0x69, 0x58, 0x0c,
	0xc9, 0xf5, 0x22, 0x09, 0x07, 0x54, 0x2f, 0xb0, 0x1a, 0x37, 0xb5, 0x14, 0xf4, 0xb2, 0xc8, 0xd7,
	0xe7, 0x77, 0xb7, 0xd5, 0x1f, 0x36, 0xaf, 0x8e, 0xf5, 0x36, 0x13, 0x93, 0xfb, 0xd9, 0x6b, 0x8e,
	0xce, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xdb, 0xd4, 0x35, 0xc5, 0x01, 0x00, 0x00,
}
